 
  const userActionTypes={
    SET_CURRENT_USER :"SET_CURRENT_USER",
    GOOGLE_SIGN_IN_START:"GOOGLE_SIGN_IN_START", 
    EMAIL_SIGN_IN_START:"EMAIL_SIGN_IN_START",
    SIGN_IN_SUCCES:"SIGN_IN_SUCCES",
    SIGN_IN_FALIUR:"SIGN_IN_FALIUR",
    CHECK_USER_SESSION:"CHECK_USER_SESSION",
    SIGN_OUT_START:"SIGN_OUT_START",
    SIGN_OUT_SUCCES:"SIGN_OUT_SUCSES",
    SIGN_OUT_FAIL:"SIGN_OUT_FAIL",
    SIGN_UP_START:"SIGN_UP_START",
    SIGN_UP_SUCCES:"SIGN_UP_SUCCES",
    SIGN_UP_FALIUR:"SIGN_UP_FALIUR",



 }
 export default userActionTypes